# pull official base image
# FROM node:16.17.1
FROM node:18

# set work directory
WORKDIR /usr/src/app/

# copy project backend
COPY ./backend ./backend

# copy project frontend
COPY ./frontend ./frontend

# set work directory
WORKDIR /usr/src/app/frontend

# copy dependencies
COPY ./package*.json .

# install dependencies
#RUN npm install -g rollup
RUN npm install

# copy project
COPY . .

EXPOSE 5000

# run container
# CMD [ "npm", "run", "dev" ]