version: '0.0.1'
services:
  backend:
    container_name: backend
    build: 
      context: ./docker/backend
      dockerfile: Dockerfile
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./backend/:/usr/src/app/
      - ./test_db/:/usr/src/app/db
    ports:
      - 20500:5000
    env_file:
      - ./docker/backend/.env.dev