/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as AppProjectProjectIdRouteRouteImport } from './routes/_app/project.$projectId/route'
import { Route as AppProjectsAddIndexRouteImport } from './routes/_app/projects/add/index'
import { Route as AppPlatePlateIdIndexRouteImport } from './routes/_app/plate.$plateId/index'
import { Route as AppObservationObservationIdIndexRouteImport } from './routes/_app/observation.$observationId/index'
import { Route as AppProjectProjectIdSettingsIndexRouteImport } from './routes/_app/project.$projectId/settings/index'
import { Route as AppObservationObservationIdCalibrateIndexRouteImport } from './routes/_app/observation.$observationId/calibrate/index'
import { ServerRoute as AppPlatePlateIdPreviewServerRouteImport } from './routes/_app/plate.$plateId/preview'
import { ServerRoute as AppObservationObservationIdPreviewServerRouteImport } from './routes/_app/observation.$observationId/preview'
import { ServerRoute as AppObservationObservationIdImageServerRouteImport } from './routes/_app/observation.$observationId/image'
import { ServerRoute as authApiAuthSplatServerRouteImport } from './routes/(auth)/api.auth.$'

const rootServerRouteImport = createServerRootRoute()

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => authRouteRoute,
} as any)
const AppProjectProjectIdRouteRoute =
  AppProjectProjectIdRouteRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppProjectsAddIndexRoute = AppProjectsAddIndexRouteImport.update({
  id: '/projects/add/',
  path: '/projects/add/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlatePlateIdIndexRoute = AppPlatePlateIdIndexRouteImport.update({
  id: '/plate/$plateId/',
  path: '/plate/$plateId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppObservationObservationIdIndexRoute =
  AppObservationObservationIdIndexRouteImport.update({
    id: '/observation/$observationId/',
    path: '/observation/$observationId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppProjectProjectIdSettingsIndexRoute =
  AppProjectProjectIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppProjectProjectIdRouteRoute,
  } as any)
const AppObservationObservationIdCalibrateIndexRoute =
  AppObservationObservationIdCalibrateIndexRouteImport.update({
    id: '/observation/$observationId/calibrate/',
    path: '/observation/$observationId/calibrate/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppPlatePlateIdPreviewServerRoute =
  AppPlatePlateIdPreviewServerRouteImport.update({
    id: '/_app/plate/$plateId/preview',
    path: '/plate/$plateId/preview',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const AppObservationObservationIdPreviewServerRoute =
  AppObservationObservationIdPreviewServerRouteImport.update({
    id: '/_app/observation/$observationId/preview',
    path: '/observation/$observationId/preview',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const AppObservationObservationIdImageServerRoute =
  AppObservationObservationIdImageServerRouteImport.update({
    id: '/_app/observation/$observationId/image',
    path: '/observation/$observationId/image',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const authApiAuthSplatServerRoute = authApiAuthSplatServerRouteImport.update({
  id: '/(auth)/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof authRouteRouteWithChildren
  '/project/$projectId': typeof AppProjectProjectIdRouteRouteWithChildren
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/observation/$observationId': typeof AppObservationObservationIdIndexRoute
  '/plate/$plateId': typeof AppPlatePlateIdIndexRoute
  '/projects/add': typeof AppProjectsAddIndexRoute
  '/observation/$observationId/calibrate': typeof AppObservationObservationIdCalibrateIndexRoute
  '/project/$projectId/settings': typeof AppProjectProjectIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authRouteRouteWithChildren
  '/project/$projectId': typeof AppProjectProjectIdRouteRouteWithChildren
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/observation/$observationId': typeof AppObservationObservationIdIndexRoute
  '/plate/$plateId': typeof AppPlatePlateIdIndexRoute
  '/projects/add': typeof AppProjectsAddIndexRoute
  '/observation/$observationId/calibrate': typeof AppObservationObservationIdCalibrateIndexRoute
  '/project/$projectId/settings': typeof AppProjectProjectIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/project/$projectId': typeof AppProjectProjectIdRouteRouteWithChildren
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/observation/$observationId/': typeof AppObservationObservationIdIndexRoute
  '/_app/plate/$plateId/': typeof AppPlatePlateIdIndexRoute
  '/_app/projects/add/': typeof AppProjectsAddIndexRoute
  '/_app/observation/$observationId/calibrate/': typeof AppObservationObservationIdCalibrateIndexRoute
  '/_app/project/$projectId/settings/': typeof AppProjectProjectIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/project/$projectId'
    | '/login'
    | '/register'
    | '/projects'
    | '/settings'
    | '/observation/$observationId'
    | '/plate/$plateId'
    | '/projects/add'
    | '/observation/$observationId/calibrate'
    | '/project/$projectId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/project/$projectId'
    | '/login'
    | '/register'
    | '/projects'
    | '/settings'
    | '/observation/$observationId'
    | '/plate/$plateId'
    | '/projects/add'
    | '/observation/$observationId/calibrate'
    | '/project/$projectId/settings'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/_app'
    | '/_app/project/$projectId'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/_app/projects/'
    | '/_app/settings/'
    | '/_app/observation/$observationId/'
    | '/_app/plate/$plateId/'
    | '/_app/projects/add/'
    | '/_app/observation/$observationId/calibrate/'
    | '/_app/project/$projectId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof authApiAuthSplatServerRoute
  '/observation/$observationId/image': typeof AppObservationObservationIdImageServerRoute
  '/observation/$observationId/preview': typeof AppObservationObservationIdPreviewServerRoute
  '/plate/$plateId/preview': typeof AppPlatePlateIdPreviewServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof authApiAuthSplatServerRoute
  '/observation/$observationId/image': typeof AppObservationObservationIdImageServerRoute
  '/observation/$observationId/preview': typeof AppObservationObservationIdPreviewServerRoute
  '/plate/$plateId/preview': typeof AppPlatePlateIdPreviewServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/(auth)/api/auth/$': typeof authApiAuthSplatServerRoute
  '/_app/observation/$observationId/image': typeof AppObservationObservationIdImageServerRoute
  '/_app/observation/$observationId/preview': typeof AppObservationObservationIdPreviewServerRoute
  '/_app/plate/$plateId/preview': typeof AppPlatePlateIdPreviewServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/auth/$'
    | '/observation/$observationId/image'
    | '/observation/$observationId/preview'
    | '/plate/$plateId/preview'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/auth/$'
    | '/observation/$observationId/image'
    | '/observation/$observationId/preview'
    | '/plate/$plateId/preview'
  id:
    | '__root__'
    | '/(auth)/api/auth/$'
    | '/_app/observation/$observationId/image'
    | '/_app/observation/$observationId/preview'
    | '/_app/plate/$plateId/preview'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  authApiAuthSplatServerRoute: typeof authApiAuthSplatServerRoute
  AppObservationObservationIdImageServerRoute: typeof AppObservationObservationIdImageServerRoute
  AppObservationObservationIdPreviewServerRoute: typeof AppObservationObservationIdPreviewServerRoute
  AppPlatePlateIdPreviewServerRoute: typeof AppPlatePlateIdPreviewServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_app/project/$projectId': {
      id: '/_app/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof AppProjectProjectIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects/add/': {
      id: '/_app/projects/add/'
      path: '/projects/add'
      fullPath: '/projects/add'
      preLoaderRoute: typeof AppProjectsAddIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/plate/$plateId/': {
      id: '/_app/plate/$plateId/'
      path: '/plate/$plateId'
      fullPath: '/plate/$plateId'
      preLoaderRoute: typeof AppPlatePlateIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/observation/$observationId/': {
      id: '/_app/observation/$observationId/'
      path: '/observation/$observationId'
      fullPath: '/observation/$observationId'
      preLoaderRoute: typeof AppObservationObservationIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/project/$projectId/settings/': {
      id: '/_app/project/$projectId/settings/'
      path: '/settings'
      fullPath: '/project/$projectId/settings'
      preLoaderRoute: typeof AppProjectProjectIdSettingsIndexRouteImport
      parentRoute: typeof AppProjectProjectIdRouteRoute
    }
    '/_app/observation/$observationId/calibrate/': {
      id: '/_app/observation/$observationId/calibrate/'
      path: '/observation/$observationId/calibrate'
      fullPath: '/observation/$observationId/calibrate'
      preLoaderRoute: typeof AppObservationObservationIdCalibrateIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/_app/plate/$plateId/preview': {
      id: '/_app/plate/$plateId/preview'
      path: '/plate/$plateId/preview'
      fullPath: '/plate/$plateId/preview'
      preLoaderRoute: typeof AppPlatePlateIdPreviewServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/_app/observation/$observationId/preview': {
      id: '/_app/observation/$observationId/preview'
      path: '/observation/$observationId/preview'
      fullPath: '/observation/$observationId/preview'
      preLoaderRoute: typeof AppObservationObservationIdPreviewServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/_app/observation/$observationId/image': {
      id: '/_app/observation/$observationId/image'
      path: '/observation/$observationId/image'
      fullPath: '/observation/$observationId/image'
      preLoaderRoute: typeof AppObservationObservationIdImageServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/(auth)/api/auth/$': {
      id: '/(auth)/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof authApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AppProjectProjectIdRouteRouteChildren {
  AppProjectProjectIdSettingsIndexRoute: typeof AppProjectProjectIdSettingsIndexRoute
}

const AppProjectProjectIdRouteRouteChildren: AppProjectProjectIdRouteRouteChildren =
  {
    AppProjectProjectIdSettingsIndexRoute:
      AppProjectProjectIdSettingsIndexRoute,
  }

const AppProjectProjectIdRouteRouteWithChildren =
  AppProjectProjectIdRouteRoute._addFileChildren(
    AppProjectProjectIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppProjectProjectIdRouteRoute: typeof AppProjectProjectIdRouteRouteWithChildren
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppObservationObservationIdIndexRoute: typeof AppObservationObservationIdIndexRoute
  AppPlatePlateIdIndexRoute: typeof AppPlatePlateIdIndexRoute
  AppProjectsAddIndexRoute: typeof AppProjectsAddIndexRoute
  AppObservationObservationIdCalibrateIndexRoute: typeof AppObservationObservationIdCalibrateIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProjectProjectIdRouteRoute: AppProjectProjectIdRouteRouteWithChildren,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppObservationObservationIdIndexRoute: AppObservationObservationIdIndexRoute,
  AppPlatePlateIdIndexRoute: AppPlatePlateIdIndexRoute,
  AppProjectsAddIndexRoute: AppProjectsAddIndexRoute,
  AppObservationObservationIdCalibrateIndexRoute:
    AppObservationObservationIdCalibrateIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  authApiAuthSplatServerRoute: authApiAuthSplatServerRoute,
  AppObservationObservationIdImageServerRoute:
    AppObservationObservationIdImageServerRoute,
  AppObservationObservationIdPreviewServerRoute:
    AppObservationObservationIdPreviewServerRoute,
  AppPlatePlateIdPreviewServerRoute: AppPlatePlateIdPreviewServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
