/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppProjectProjectIdRouteRouteImport } from './routes/_app/project.$projectId/route'
import { Route as AppPlatePlateIdIndexRouteImport } from './routes/_app/plate.$plateId/index'
import { Route as AppObservationObservationIdIndexRouteImport } from './routes/_app/observation.$observationId/index'
import { Route as AppObservationObservationIdCalibrateIndexRouteImport } from './routes/_app/observation.$observationId/calibrate/index'
import { ServerRoute as AppPlatePlateIdPreviewServerRouteImport } from './routes/_app/plate.$plateId/preview'
import { ServerRoute as AppObservationObservationIdPreviewServerRouteImport } from './routes/_app/observation.$observationId/preview'
import { ServerRoute as AppObservationObservationIdImageServerRouteImport } from './routes/_app/observation.$observationId/image'
import { ServerRoute as authApiAuthSplatServerRouteImport } from './routes/(auth)/api.auth.$'

const rootServerRouteImport = createServerRootRoute()

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectProjectIdRouteRoute =
  AppProjectProjectIdRouteRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppPlatePlateIdIndexRoute = AppPlatePlateIdIndexRouteImport.update({
  id: '/plate/$plateId/',
  path: '/plate/$plateId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppObservationObservationIdIndexRoute =
  AppObservationObservationIdIndexRouteImport.update({
    id: '/observation/$observationId/',
    path: '/observation/$observationId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppObservationObservationIdCalibrateIndexRoute =
  AppObservationObservationIdCalibrateIndexRouteImport.update({
    id: '/observation/$observationId/calibrate/',
    path: '/observation/$observationId/calibrate/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppPlatePlateIdPreviewServerRoute =
  AppPlatePlateIdPreviewServerRouteImport.update({
    id: '/_app/plate/$plateId/preview',
    path: '/plate/$plateId/preview',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const AppObservationObservationIdPreviewServerRoute =
  AppObservationObservationIdPreviewServerRouteImport.update({
    id: '/_app/observation/$observationId/preview',
    path: '/observation/$observationId/preview',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const AppObservationObservationIdImageServerRoute =
  AppObservationObservationIdImageServerRouteImport.update({
    id: '/_app/observation/$observationId/image',
    path: '/observation/$observationId/image',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const authApiAuthSplatServerRoute = authApiAuthSplatServerRouteImport.update({
  id: '/(auth)/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/project/$projectId': typeof AppProjectProjectIdRouteRoute
  '/projects': typeof AppProjectsIndexRoute
  '/observation/$observationId': typeof AppObservationObservationIdIndexRoute
  '/plate/$plateId': typeof AppPlatePlateIdIndexRoute
  '/observation/$observationId/calibrate': typeof AppObservationObservationIdCalibrateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/project/$projectId': typeof AppProjectProjectIdRouteRoute
  '/projects': typeof AppProjectsIndexRoute
  '/observation/$observationId': typeof AppObservationObservationIdIndexRoute
  '/plate/$plateId': typeof AppPlatePlateIdIndexRoute
  '/observation/$observationId/calibrate': typeof AppObservationObservationIdCalibrateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/_app/project/$projectId': typeof AppProjectProjectIdRouteRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/observation/$observationId/': typeof AppObservationObservationIdIndexRoute
  '/_app/plate/$plateId/': typeof AppPlatePlateIdIndexRoute
  '/_app/observation/$observationId/calibrate/': typeof AppObservationObservationIdCalibrateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/login/'
    | '/settings/'
    | '/project/$projectId'
    | '/projects'
    | '/observation/$observationId'
    | '/plate/$plateId'
    | '/observation/$observationId/calibrate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/project/$projectId'
    | '/projects'
    | '/observation/$observationId'
    | '/plate/$plateId'
    | '/observation/$observationId/calibrate'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/settings'
    | '/login/'
    | '/settings/'
    | '/_app/project/$projectId'
    | '/_app/projects/'
    | '/_app/observation/$observationId/'
    | '/_app/plate/$plateId/'
    | '/_app/observation/$observationId/calibrate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof authApiAuthSplatServerRoute
  '/observation/$observationId/image': typeof AppObservationObservationIdImageServerRoute
  '/observation/$observationId/preview': typeof AppObservationObservationIdPreviewServerRoute
  '/plate/$plateId/preview': typeof AppPlatePlateIdPreviewServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof authApiAuthSplatServerRoute
  '/observation/$observationId/image': typeof AppObservationObservationIdImageServerRoute
  '/observation/$observationId/preview': typeof AppObservationObservationIdPreviewServerRoute
  '/plate/$plateId/preview': typeof AppPlatePlateIdPreviewServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/(auth)/api/auth/$': typeof authApiAuthSplatServerRoute
  '/_app/observation/$observationId/image': typeof AppObservationObservationIdImageServerRoute
  '/_app/observation/$observationId/preview': typeof AppObservationObservationIdPreviewServerRoute
  '/_app/plate/$plateId/preview': typeof AppPlatePlateIdPreviewServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/auth/$'
    | '/observation/$observationId/image'
    | '/observation/$observationId/preview'
    | '/plate/$plateId/preview'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/auth/$'
    | '/observation/$observationId/image'
    | '/observation/$observationId/preview'
    | '/plate/$plateId/preview'
  id:
    | '__root__'
    | '/(auth)/api/auth/$'
    | '/_app/observation/$observationId/image'
    | '/_app/observation/$observationId/preview'
    | '/_app/plate/$plateId/preview'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  authApiAuthSplatServerRoute: typeof authApiAuthSplatServerRoute
  AppObservationObservationIdImageServerRoute: typeof AppObservationObservationIdImageServerRoute
  AppObservationObservationIdPreviewServerRoute: typeof AppObservationObservationIdPreviewServerRoute
  AppPlatePlateIdPreviewServerRoute: typeof AppPlatePlateIdPreviewServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/project/$projectId': {
      id: '/_app/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof AppProjectProjectIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/plate/$plateId/': {
      id: '/_app/plate/$plateId/'
      path: '/plate/$plateId'
      fullPath: '/plate/$plateId'
      preLoaderRoute: typeof AppPlatePlateIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/observation/$observationId/': {
      id: '/_app/observation/$observationId/'
      path: '/observation/$observationId'
      fullPath: '/observation/$observationId'
      preLoaderRoute: typeof AppObservationObservationIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/observation/$observationId/calibrate/': {
      id: '/_app/observation/$observationId/calibrate/'
      path: '/observation/$observationId/calibrate'
      fullPath: '/observation/$observationId/calibrate'
      preLoaderRoute: typeof AppObservationObservationIdCalibrateIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/_app/plate/$plateId/preview': {
      id: '/_app/plate/$plateId/preview'
      path: '/plate/$plateId/preview'
      fullPath: '/plate/$plateId/preview'
      preLoaderRoute: typeof AppPlatePlateIdPreviewServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/_app/observation/$observationId/preview': {
      id: '/_app/observation/$observationId/preview'
      path: '/observation/$observationId/preview'
      fullPath: '/observation/$observationId/preview'
      preLoaderRoute: typeof AppObservationObservationIdPreviewServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/_app/observation/$observationId/image': {
      id: '/_app/observation/$observationId/image'
      path: '/observation/$observationId/image'
      fullPath: '/observation/$observationId/image'
      preLoaderRoute: typeof AppObservationObservationIdImageServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/(auth)/api/auth/$': {
      id: '/(auth)/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof authApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppProjectProjectIdRouteRoute: typeof AppProjectProjectIdRouteRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppObservationObservationIdIndexRoute: typeof AppObservationObservationIdIndexRoute
  AppPlatePlateIdIndexRoute: typeof AppPlatePlateIdIndexRoute
  AppObservationObservationIdCalibrateIndexRoute: typeof AppObservationObservationIdCalibrateIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProjectProjectIdRouteRoute: AppProjectProjectIdRouteRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppObservationObservationIdIndexRoute: AppObservationObservationIdIndexRoute,
  AppPlatePlateIdIndexRoute: AppPlatePlateIdIndexRoute,
  AppObservationObservationIdCalibrateIndexRoute:
    AppObservationObservationIdCalibrateIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  authApiAuthSplatServerRoute: authApiAuthSplatServerRoute,
  AppObservationObservationIdImageServerRoute:
    AppObservationObservationIdImageServerRoute,
  AppObservationObservationIdPreviewServerRoute:
    AppObservationObservationIdPreviewServerRoute,
  AppPlatePlateIdPreviewServerRoute: AppPlatePlateIdPreviewServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
