/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as AppProjectsAddIndexRouteImport } from './routes/_app/projects/add/index'
import { Route as AppProjectProjectIdIndexRouteImport } from './routes/_app/project.$projectId/index'
import { Route as AppPlatePlateIdIndexRouteImport } from './routes/_app/plate.$plateId/index'
import { Route as AppObservationObservationIdIndexRouteImport } from './routes/_app/observation.$observationId/index'
import { Route as AppPlatePlateIdPreviewRouteImport } from './routes/_app/plate.$plateId/preview'
import { Route as AppObservationObservationIdPreviewRouteImport } from './routes/_app/observation.$observationId/preview'
import { Route as AppObservationObservationIdImageRouteImport } from './routes/_app/observation.$observationId/image'
import { Route as authApiAuthSplatRouteImport } from './routes/(auth)/api.auth.$'
import { Route as AppProjectProjectIdSettingsIndexRouteImport } from './routes/_app/project.$projectId/settings/index'
import { Route as AppObservationObservationIdCalibrateIndexRouteImport } from './routes/_app/observation.$observationId/calibrate/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => authRouteRoute,
} as any)
const AppProjectsAddIndexRoute = AppProjectsAddIndexRouteImport.update({
  id: '/projects/add/',
  path: '/projects/add/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectProjectIdIndexRoute =
  AppProjectProjectIdIndexRouteImport.update({
    id: '/project/$projectId/',
    path: '/project/$projectId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppPlatePlateIdIndexRoute = AppPlatePlateIdIndexRouteImport.update({
  id: '/plate/$plateId/',
  path: '/plate/$plateId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppObservationObservationIdIndexRoute =
  AppObservationObservationIdIndexRouteImport.update({
    id: '/observation/$observationId/',
    path: '/observation/$observationId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppPlatePlateIdPreviewRoute = AppPlatePlateIdPreviewRouteImport.update({
  id: '/plate/$plateId/preview',
  path: '/plate/$plateId/preview',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppObservationObservationIdPreviewRoute =
  AppObservationObservationIdPreviewRouteImport.update({
    id: '/observation/$observationId/preview',
    path: '/observation/$observationId/preview',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppObservationObservationIdImageRoute =
  AppObservationObservationIdImageRouteImport.update({
    id: '/observation/$observationId/image',
    path: '/observation/$observationId/image',
    getParentRoute: () => AppRouteRoute,
  } as any)
const authApiAuthSplatRoute = authApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => authRouteRoute,
} as any)
const AppProjectProjectIdSettingsIndexRoute =
  AppProjectProjectIdSettingsIndexRouteImport.update({
    id: '/project/$projectId/settings/',
    path: '/project/$projectId/settings/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppObservationObservationIdCalibrateIndexRoute =
  AppObservationObservationIdCalibrateIndexRouteImport.update({
    id: '/observation/$observationId/calibrate/',
    path: '/observation/$observationId/calibrate/',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/api/auth/$': typeof authApiAuthSplatRoute
  '/observation/$observationId/image': typeof AppObservationObservationIdImageRoute
  '/observation/$observationId/preview': typeof AppObservationObservationIdPreviewRoute
  '/plate/$plateId/preview': typeof AppPlatePlateIdPreviewRoute
  '/observation/$observationId': typeof AppObservationObservationIdIndexRoute
  '/plate/$plateId': typeof AppPlatePlateIdIndexRoute
  '/project/$projectId': typeof AppProjectProjectIdIndexRoute
  '/projects/add': typeof AppProjectsAddIndexRoute
  '/observation/$observationId/calibrate': typeof AppObservationObservationIdCalibrateIndexRoute
  '/project/$projectId/settings': typeof AppProjectProjectIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/api/auth/$': typeof authApiAuthSplatRoute
  '/observation/$observationId/image': typeof AppObservationObservationIdImageRoute
  '/observation/$observationId/preview': typeof AppObservationObservationIdPreviewRoute
  '/plate/$plateId/preview': typeof AppPlatePlateIdPreviewRoute
  '/observation/$observationId': typeof AppObservationObservationIdIndexRoute
  '/plate/$plateId': typeof AppPlatePlateIdIndexRoute
  '/project/$projectId': typeof AppProjectProjectIdIndexRoute
  '/projects/add': typeof AppProjectsAddIndexRoute
  '/observation/$observationId/calibrate': typeof AppObservationObservationIdCalibrateIndexRoute
  '/project/$projectId/settings': typeof AppProjectProjectIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_app': typeof AppRouteRouteWithChildren
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/(auth)/api/auth/$': typeof authApiAuthSplatRoute
  '/_app/observation/$observationId/image': typeof AppObservationObservationIdImageRoute
  '/_app/observation/$observationId/preview': typeof AppObservationObservationIdPreviewRoute
  '/_app/plate/$plateId/preview': typeof AppPlatePlateIdPreviewRoute
  '/_app/observation/$observationId/': typeof AppObservationObservationIdIndexRoute
  '/_app/plate/$plateId/': typeof AppPlatePlateIdIndexRoute
  '/_app/project/$projectId/': typeof AppProjectProjectIdIndexRoute
  '/_app/projects/add/': typeof AppProjectsAddIndexRoute
  '/_app/observation/$observationId/calibrate/': typeof AppObservationObservationIdCalibrateIndexRoute
  '/_app/project/$projectId/settings/': typeof AppProjectProjectIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/projects'
    | '/settings'
    | '/api/auth/$'
    | '/observation/$observationId/image'
    | '/observation/$observationId/preview'
    | '/plate/$plateId/preview'
    | '/observation/$observationId'
    | '/plate/$plateId'
    | '/project/$projectId'
    | '/projects/add'
    | '/observation/$observationId/calibrate'
    | '/project/$projectId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/projects'
    | '/settings'
    | '/api/auth/$'
    | '/observation/$observationId/image'
    | '/observation/$observationId/preview'
    | '/plate/$plateId/preview'
    | '/observation/$observationId'
    | '/plate/$plateId'
    | '/project/$projectId'
    | '/projects/add'
    | '/observation/$observationId/calibrate'
    | '/project/$projectId/settings'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/_app'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/_app/projects/'
    | '/_app/settings/'
    | '/(auth)/api/auth/$'
    | '/_app/observation/$observationId/image'
    | '/_app/observation/$observationId/preview'
    | '/_app/plate/$plateId/preview'
    | '/_app/observation/$observationId/'
    | '/_app/plate/$plateId/'
    | '/_app/project/$projectId/'
    | '/_app/projects/add/'
    | '/_app/observation/$observationId/calibrate/'
    | '/_app/project/$projectId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_app/projects/add/': {
      id: '/_app/projects/add/'
      path: '/projects/add'
      fullPath: '/projects/add'
      preLoaderRoute: typeof AppProjectsAddIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/project/$projectId/': {
      id: '/_app/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof AppProjectProjectIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/plate/$plateId/': {
      id: '/_app/plate/$plateId/'
      path: '/plate/$plateId'
      fullPath: '/plate/$plateId'
      preLoaderRoute: typeof AppPlatePlateIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/observation/$observationId/': {
      id: '/_app/observation/$observationId/'
      path: '/observation/$observationId'
      fullPath: '/observation/$observationId'
      preLoaderRoute: typeof AppObservationObservationIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/plate/$plateId/preview': {
      id: '/_app/plate/$plateId/preview'
      path: '/plate/$plateId/preview'
      fullPath: '/plate/$plateId/preview'
      preLoaderRoute: typeof AppPlatePlateIdPreviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/observation/$observationId/preview': {
      id: '/_app/observation/$observationId/preview'
      path: '/observation/$observationId/preview'
      fullPath: '/observation/$observationId/preview'
      preLoaderRoute: typeof AppObservationObservationIdPreviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/observation/$observationId/image': {
      id: '/_app/observation/$observationId/image'
      path: '/observation/$observationId/image'
      fullPath: '/observation/$observationId/image'
      preLoaderRoute: typeof AppObservationObservationIdImageRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/api/auth/$': {
      id: '/(auth)/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof authApiAuthSplatRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_app/project/$projectId/settings/': {
      id: '/_app/project/$projectId/settings/'
      path: '/project/$projectId/settings'
      fullPath: '/project/$projectId/settings'
      preLoaderRoute: typeof AppProjectProjectIdSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/observation/$observationId/calibrate/': {
      id: '/_app/observation/$observationId/calibrate/'
      path: '/observation/$observationId/calibrate'
      fullPath: '/observation/$observationId/calibrate'
      preLoaderRoute: typeof AppObservationObservationIdCalibrateIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
  authApiAuthSplatRoute: typeof authApiAuthSplatRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
  authApiAuthSplatRoute: authApiAuthSplatRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppObservationObservationIdImageRoute: typeof AppObservationObservationIdImageRoute
  AppObservationObservationIdPreviewRoute: typeof AppObservationObservationIdPreviewRoute
  AppPlatePlateIdPreviewRoute: typeof AppPlatePlateIdPreviewRoute
  AppObservationObservationIdIndexRoute: typeof AppObservationObservationIdIndexRoute
  AppPlatePlateIdIndexRoute: typeof AppPlatePlateIdIndexRoute
  AppProjectProjectIdIndexRoute: typeof AppProjectProjectIdIndexRoute
  AppProjectsAddIndexRoute: typeof AppProjectsAddIndexRoute
  AppObservationObservationIdCalibrateIndexRoute: typeof AppObservationObservationIdCalibrateIndexRoute
  AppProjectProjectIdSettingsIndexRoute: typeof AppProjectProjectIdSettingsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppObservationObservationIdImageRoute: AppObservationObservationIdImageRoute,
  AppObservationObservationIdPreviewRoute:
    AppObservationObservationIdPreviewRoute,
  AppPlatePlateIdPreviewRoute: AppPlatePlateIdPreviewRoute,
  AppObservationObservationIdIndexRoute: AppObservationObservationIdIndexRoute,
  AppPlatePlateIdIndexRoute: AppPlatePlateIdIndexRoute,
  AppProjectProjectIdIndexRoute: AppProjectProjectIdIndexRoute,
  AppProjectsAddIndexRoute: AppProjectsAddIndexRoute,
  AppObservationObservationIdCalibrateIndexRoute:
    AppObservationObservationIdCalibrateIndexRoute,
  AppProjectProjectIdSettingsIndexRoute: AppProjectProjectIdSettingsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
