export const observatories = [
    { label: 'ctio: Cerro Tololo Interamerican Observatory', value: "ctio: Cerro Tololo Interamerican Observatory", lat: -30.169, lon: -70.806 },
    { label: 'kpno: Kitt Peak National Observatory', value: "kpno: Kitt Peak National Observatory", lat: 31.958, lon: -111.598 },
    { label: 'casleo: Complejo Astronomico El Leoncito, San Juan', value: "casleo: Complejo Astronomico El Leoncito, San Juan", lat: -31.798, lon: -69.295 },
    { label: 'wiyn: WIYN Observatory', value: "wiyn: WIYN Observatory", lat: 31.958, lon: -111.598 },
    { label: 'lasilla: European Southern Observatory: La Silla', value: "lasilla: European Southern Observatory: La Silla", lat: -29.258, lon: -70.734 },
    { label: 'paranal: European Southern Observatory: Paranal', value: "paranal: European Southern Observatory: Paranal", lat: -24.625, lon: -70.404 },
    { label: 'lick: Lick Observatory', value: "lick: Lick Observatory", lat: 37.342, lon: -121.642 },
    { label: 'mmto: MMT Observatory', value: "mmto: MMT Observatory", lat: 31.688, lon: -110.885 },
    { label: 'cfht: Canada-France-Hawaii Telescope', value: "cfht: Canada-France-Hawaii Telescope", lat: 19.826, lon: -155.474 },
    { label: 'lapalma: Roque de los Muchachos, La Palma', value: "lapalma: Roque de los Muchachos, La Palma", lat: 28.758, lon: -17.889 },
    { label: 'mso: Mt. Stromlo Observatory', value: "mso: Mt. Stromlo Observatory", lat: -35.319, lon: 149.009 },
    { label: 'sso: Siding Spring Observatory', value: "sso: Siding Spring Observatory", lat: -31.273, lon: 149.067 },
    { label: 'aao: Anglo-Australian Observatory', value: "aao: Anglo-Australian Observatory", lat: -31.277, lon: 149.067 },
    { label: 'mcdonald: McDonald Observatory', value: "mcdonald: McDonald Observatory", lat: 30.671, lon: -104.015 },
    { label: 'lco: Las Campanas Observatory', value: "lco: Las Campanas Observatory", lat: -29.015, lon: -70.692 },
    { label: 'mtbigelow: Catalina Observatory: 61 inch telescope', value: "mtbigelow: Catalina Observatory: 61 inch telescope", lat: 32.417, lon: -110.733 },
    { label: 'dao: Dominion Astrophysical Observatory', value: "dao: Dominion Astrophysical Observatory", lat: 48.520, lon: -123.416 },
    { label: 'spm: Observatorio Astronomico Nacional, San Pedro Martir', value: "spm: Observatorio Astronomico Nacional, San Pedro Martir", lat: 31.045, lon: -115.465 },
    { label: 'tona: Observatorio Astronomico Nacional, Tonantzintla', value: "tona: Observatorio Astronomico Nacional, Tonantzintla", lat: 19.029, lon: -98.302 },
    { label: 'Palomar: The Hale Telescope', value: "Palomar: The Hale Telescope", lat: 33.356, lon: -116.864 },
    { label: 'mdm: Michigan-Dartmouth-MIT Observatory', value: "mdm: Michigan-Dartmouth-MIT Observatory", lat: 31.688, lon: -110.885 },
    { label: 'NOV: National Observatory of Venezuela', value: "NOV: National Observatory of Venezuela", lat: 8.785, lon: -71.195 },
    { label: 'bmo: Black Moshannon Observatory', value: "bmo: Black Moshannon Observatory", lat: 40.912, lon: -78.056 },
    { label: 'BAO: Beijing XingLong Observatory', value: "BAO: Beijing XingLong Observatory", lat: 40.395, lon: 117.585 },
    { label: 'keck: W. M. Keck Observatory', value: "keck: W. M. Keck Observatory", lat: 19.826, lon: -155.474 },
    { label: 'ekar: Mt. Ekar 182 cm. Telescope', value: "ekar: Mt. Ekar 182 cm. Telescope", lat: 45.834, lon: 11.571 },
    { label: 'apo: Apache Point Observatory', value: "apo: Apache Point Observatory", lat: 32.780, lon: -105.820 },
    { label: 'lowell: Lowell Observatory', value: "lowell: Lowell Observatory", lat: 35.203, lon: -111.664 },
    { label: 'vbo: Vainu Bappu Observatory', value: "vbo: Vainu Bappu Observatory", lat: 12.579, lon: 78.824 },
    { label: 'iao: Indian Astronomical Observatory, Hanle', value: "iao: Indian Astronomical Observatory, Hanle", lat: 32.779, lon: 78.964 },
    { label: 'flwo: Whipple Observatory', value: "flwo: Whipple Observatory", lat: 31.688, lon: -110.885 },
    { label: 'oro: Oak Ridge Observatory', value: "oro: Oak Ridge Observatory", lat: 42.503, lon: -71.586 },
    { label: 'lna: Laboratorio Nacional de Astrofisica - Brazil', value: "lna: Laboratorio Nacional de Astrofisica - Brazil", lat: -22.535, lon: -45.582 },
    { label: 'saao: South African Astronomical Observatory', value: "saao: South African Astronomical Observatory", lat: -32.379, lon: 20.810 },
    { label: 'bosque: Estacion Astrofisica Bosque Alegre, Cordoba', value: "bosque: Estacion Astrofisica Bosque Alegre, Cordoba", lat: -31.598, lon: -64.546 },
    { label: 'rozhen: National Astronomical Observatory Rozhen - Bulgaria', value: "rozhen: National Astronomical Observatory Rozhen - Bulgaria", lat: 41.694, lon: 24.741 },
    { label: 'irtf: NASA Infrared Telescope Facility', value: "irtf: NASA Infrared Telescope Facility", lat: 19.826, lon: -155.474 },
    { label: 'bgsuo: Bowling Green State Univ Observatory', value: "bgsuo: Bowling Green State Univ Observatory", lat: 41.3776, lon: -83.6386 },
    { label: 'DSAZ: Deutsch-Spanisches Observatorium Calar Alto - Spain', value: "DSAZ: Deutsch-Spanisches Observatorium Calar Alto - Spain", lat: 37.2236, lon: -2.5463 },
    { label: 'ca: Calar Alto Observatory', value: "ca: Calar Alto Observatory", lat: 37.2236, lon: -2.5463 },
    { label: 'holi: Observatorium Hoher List (Universitaet Bonn) - Germany', value: "holi: Observatorium Hoher List (Universitaet Bonn) - Germany", lat: 50.2333, lon: 6.8833 },
    { label: 'lmo: Leander McCormick Observatory', value: "lmo: Leander McCormick Observatory", lat: 38.0317, lon: -78.5139 },
    { label: 'fmo: Fan Mountain Observatory', value: "fmo: Fan Mountain Observatory", lat: 37.7864, lon: -78.6578 },
    { label: 'whitin: Whitin Observatory, Wellesley College', value: "whitin: Whitin Observatory, Wellesley College", lat: 42.2933, lon: -71.3067 },
    { label: 'osn: Observatorio de Sierra Nevada', value: "osn: Observatorio de Sierra Nevada", lat: 37.0642, lon: -3.3847 },
    { label: 'gemini-north: Gemini North Observatory', value: "gemini-north: Gemini North Observatory", lat: 19.8238, lon: -155.4691 },
    { label: 'gemini-south: Gemini South Observatory', value: "gemini-south: Gemini South Observatory", lat: -30.2407, lon: -70.7366 },
    { label: 'esontt: European Southern Observatory, NTT, La Silla', value: "esontt: European Southern Observatory, NTT, La Silla", lat: -29.2584, lon: -70.7313 },
    { label: 'eso36m: European Southern Observatory, 3.6m Telescope, La Silla', value: "eso36m: European Southern Observatory, 3.6m Telescope, La Silla", lat: -29.2584, lon: -70.7313 },
    { label: 'esovlt: European Southern Observatory, VLT, Paranal', value: "esovlt: European Southern Observatory, VLT, Paranal", lat: -24.6252, lon: -70.4042 },
    { label: 'sln: SLN - Catania Astrophysical Observatory', value: "sln: SLN - Catania Astrophysical Observatory", lat: 37.6925, lon: 14.9989 },
    { label: 'euo: Ege University Observatory', value: "euo: Ege University Observatory", lat: 38.3977, lon: 27.2167 },
    { label: 'tug: TUBITAK National Observatory, Turkey', value: "tug: TUBITAK National Observatory, Turkey", lat: 36.824, lon: 30.335 },
    { label: 'mgo: Mount Graham Observatory', value: "mgo: Mount Graham Observatory", lat: 32.7013, lon: -109.8891 },
    { label: 'aries: Aryabhatta Research Institute of Observational Sciences', value: "aries: Aryabhatta Research Institute of Observational Sciences", lat: 29.364, lon: 79.461 },
    { label: 'oalp: Observatorio Astronomico de La Plata', value: "oalp: Observatorio Astronomico de La Plata", lat: -34.911, lon: -57.950 },
    { label: 'olin: Connecticut', value: "olin: Connecticut", lat: 41.3083, lon: -72.9279 },
    { label: 'boyden: Boyden', value: "boyden: Boyden", lat: -29.0456, lon: 26.4014 },
    { label: 'lulin: Lulin Observatory', value: "lulin: Lulin Observatory", lat: 23.469, lon: 120.877 },
    { label: 'soar: Southern Astrophysical Research Telescope', value: "soar: Southern Astrophysical Research Telescope", lat: -30.2407, lon: -70.7366 },
    { label: 'baker: Baker Observatory', value: "baker: Baker Observatory", lat: 37.2325, lon: -93.495 },
    { label: 'het: McDonald Observatory - Hobby-Eberly Telescope', value: "het: McDonald Observatory - Hobby-Eberly Telescope", lat: 30.6814, lon: -104.015 },
    { label: 'jcdo: Jack C. Davis Observatory, Western Nevada College', value: "jcdo: Jack C. Davis Observatory, Western Nevada College", lat: 39.2025, lon: -119.733 },
    { label: 'lno: Langkawi National Observatory', value: "lno: Langkawi National Observatory", lat: 6.306, lon: 99.779 }
]

export const getObservatoryCoords = (observat: string): { lat: number; lon: number } | null => {
    const observatory = observatories.find(obs => obs.value == observat);
    return observatory ? { lat: observatory.lat, lon: observatory.lon } : null;
}